export const PLACEHOLDERS: Array<string> = [
  "Lugar donde habitan personas",
  "Instrumento para medir la hora",
  "Lluvia fuerte e intensa",
  "Aparato antiguo para escribir textos",
  "Agua segura para beber",
  "Acertar exactamente en algo",
  "Animal doméstico para protección",
  "Persona que miente habitualmente",
  "Aparato portátil para llamadas",
  "Persona que disfruta mucho leyendo",
  "Dinero pagado por vivienda alquilada",
  "Lugar donde venden medicamentos",
  "Mantenerse tranquilo en situaciones difíciles",
  "Dar nacimiento a un bebé",
  "Persona que cuida enfermos",
  "Sueño breve durante el día",
  "Vehículo para viajes largos",
  "Reparar algo dañado o roto",
  "Comida ligera entre horas",
  "Instrumento para observar lejos",
  "Persona que conduce vehículos",
  "Buscar información en internet",
  "Realizar algo fácilmente",
  "Objeto para abrir cerraduras",
  "Bebida obtenida de frutas exprimidas",
  "Persona encargada de seguridad pública",
  "Pago por un servicio prestado",
  "Reunión informal con amigos",
  "Tristeza profunda por pérdida",
  "Instrumento musical con teclas",
  "Persona que transmite conocimientos",
  "Producto lácteo sólido",
  "Quedarse profundamente dormido",
  "Objeto usado para dibujar",
  "Hacer algo sin ganas",
  "Papel para notas rápidas",
  "Lugar público para pasear",
  "Caminar lentamente por placer",
  "Tienda donde venden libros",
  "Bebida estimulante obtenida del café",
  "Recipiente para basura",
  "Alimento horneado con harina",
  "Instrumento para peinar cabello",
  "Objeto pequeño para encender fuego",
  "Persona que come con apetito",
  "Aparato que conserva alimentos fríos",
  "Persona amable y educada",
  "Aparato que aumenta volumen",
  "Comida pequeña antes del plato principal",
  "Lugar para exhibir arte",
  "Expresar alegría por noticia buena",
  "Dejar temporalmente un lugar",
  "Aparato para regular temperatura ambiente",
  "Persona que resuelve asuntos legales",
  "Superar una situación complicada",
  "Actividad física para mejorar salud",
  "Objeto que refleja imágenes",
  "Lugar donde proyectan películas",
  "Actividad artística con pintura",
  "Aparato para enfriar espacios",
  "Persona que cuida jardines",
  "Prestar total atención a alguien",
  "Recipiente pequeño con tinta",
  "Persona que repara automóviles",
  "Objeto cómodo para sentarse",
  "Instrumento que indica dirección norte",
  "Intentar algo difícil o arriesgado",
  "Lugar para guardar documentos ordenados",
  "Objeto para proteger ojos del sol",
  "Material para escribir en pizarras",
  "Actividad relajante en tiempo libre",
  "Comprar y vender productos",
  "Lugar de venta de comida rápida",
  "Objeto para protegerse de lluvia",
  "Persona que vende pan",
  "Olvidar completamente algo",
  "Recipiente profundo para cocinar",
  "Instrumento para medir temperatura",
  "Persona que viaja frecuentemente",
  "Lugar donde se guarda ropa",
  "Instrumento para limpiar polvo",
  "Aparato usado para tomar fotos",
  "Persona que practica deportes",
  "Cocinar alimentos al fuego",
  "Enfadarse con facilidad",
  "Instrumento metálico para cortar alimentos",
  "Usar algo de nuevo",
  "Lugar para estacionar automóviles",
  "Instrumento óptico que amplía objetos",
  "Persona con mala visión lejana",
  "Objeto que muestra fechas del año",
  "Levantarse temprano por la mañana",
  "Persona que sirve bebidas alcohólicas",
  "Entender finalmente algo complejo",
  "Viajar frecuentemente por trabajo",
  "Aparato electrónico para reproducir música",
  "Descansar después de esfuerzo físico",
  "Lugar donde venden carne",
  "Tener memoria excelente",
  "Persona que atiende clientes",
  "Objeto metálico para unir papeles",
  "Expresar gratitud por algo recibido",
  "Lugar de alojamiento para viajeros",
  "Instrumento musical tocado con arco",
  "Persona que investiga científicamente",
  "Vehículo para transporte aéreo",
  "Aparato que cocina con calor",
  "Persona que dirige una empresa",
  "Lugar donde venden frutas frescas",
  "Bebida alcohólica hecha con uvas",
  "Objeto para medir longitudes pequeñas",
  "Lugar para aprender deportes",
  "Persona que escribe libros",
  "Material para limpiar dientes",
  "Recipiente para líquidos calientes",
  "Instrumento para tocar música",
  "Aparato que ilumina espacios oscuros",
  "Lugar de preparación de alimentos",
  "Objeto para guardar dinero",
  "Persona que diseña edificios",
  "Lugar donde venden pescado fresco",
  "Aparato para lavar ropa automáticamente",
  "Persona que cocina profesionalmente",
  "Instrumento que mide presión atmosférica",
  "Objeto usado para cortar papel",
  "Persona que vende medicamentos",
  "Lugar donde juegan niños",
  "Instrumento para medir velocidad",
  "Persona que pinta cuadros",
  "Recipiente para beber líquidos",
  "Lugar donde reparan automóviles",
  "Instrumento para escribir tinta",
  "Persona que fabrica muebles",
  "Objeto para medir temperatura ambiental",
  "Lugar que vende flores frescas",
  "Instrumento musical de viento",
  "Persona que organiza documentos",
  "Aparato que proyecta imágenes",
  "Lugar para reparar zapatos",
  "Objeto para sujetar ropa",
  "Persona que vende verduras",
  "Lugar para practicar natación",
  "Instrumento que mide peso",
  "Persona que revisa cuentas financieras",
  "Lugar donde venden joyas",
  "Objeto para calentar agua rápidamente",
  "Instrumento que corta césped",
  "Persona que conduce aviones",
  "Lugar para consultas médicas",
  "Objeto para medir distancias largas",
  "Persona que vende periódicos",
  "Lugar donde preparan pasteles",
  "Instrumento para medir electricidad",
  "Persona que cuida animales",
  "Objeto que sostiene libros verticalmente",
  "Lugar donde venden ropa",
  "Instrumento para escuchar sonidos médicos",
  "Persona que realiza entrevistas",
  "Lugar donde venden dulces",
  "Objeto para calentar habitaciones",
  "Instrumento para afinar instrumentos musicales",
  "Persona que interpreta idiomas",
  "Lugar donde venden antigüedades",
  "Objeto para escribir en papel carbón",
];
